services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - '3100:3000'       # HOST:CONTAINER
    env_file:
      - ./auth-service/.env

  patient-portal:
    build: ./patient-service
    container_name: patient-service
    ports:
      - '3102:3002'
    env_file:
      - ./patient-service/.env

  staff-operations:
    build: ./staff-operations
    container_name: staff-operations
    ports:
      - '3103:3003'
    env_file:
      - ./staff-operations/.env

  appointment-manager:
    build: ./appointment-manager
    container_name: appointment-manager
    ports:
      - '3104:3004'
    env_file:
      - ./appointment-manager/.env

  ward-coordinator:
    build: ./ward-coordinator
    container_name: ward-coordinator
    ports:
      - '3105:3005'
    env_file:
      - ./ward-coordinator/.env

  emergency-response:
    build: ./emergency-response
    container_name: emergency-response
    ports:
      - '3106:3006'
    env_file:
      - ./emergency-response/.env
